config/routes.rb
Rails.application.routes.draw do
  resources :battles
  devise_for :users
  get "home/index"
  get "/leaderboard", to: "home#leaderboard"

  # Defines the root path route ("/")
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :initiator, class_name: "User"
  belongs_to :opponent, class_name: "User"
  belongs_to :winner, class_name: "User", optional: true

  validates :initiator, presence: true
end

app/models/battle_log.rb
class BattleLog < ApplicationRecord
  belongs_to :battle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :initiator_battles, class_name: "Battle", foreign_key: "initiator_id"
  has_many :opponent_battles, class_name: "Battle", foreign_key: "opponent_id"
  has_many :winner_battles, class_name: "Battle", foreign_key: "winner_id"

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :amount_of_gold, :attack_value, :hit_points, :luck_value])
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :set_battle, only: %i[ show edit update destroy ]

  # GET /battles or /battles.json
  def index
    @battles = Battle.all
  end

  # GET /battles/1 or /battles/1.json
  def show
    @battle_logs = BattleLog.where(battle_id: params[:id])
  end

  # GET /battles/new
  def new
    @battle = Battle.new
  end

  # GET /battles/1/edit
  def edit
  end

  # POST /battles or /battles.json
  def create
    @battle = Battle.new(battle_params)

    respond_to do |format|
      if @battle.save
        # Battle should be executed as soon it is submitted
        BattleProcessorJob.perform_now
        format.html { redirect_to battle_url(@battle), notice: "Battle was successfully created." }
        format.json { render :show, status: :created, location: @battle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /battles/1 or /battles/1.json
  def update
    respond_to do |format|
      if @battle.update(battle_params)
        format.html { redirect_to battle_url(@battle), notice: "Battle was successfully updated." }
        format.json { render :show, status: :ok, location: @battle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /battles/1 or /battles/1.json
  def destroy
    @battle.destroy

    respond_to do |format|
      format.html { redirect_to battles_url, notice: "Battle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_battle
    @battle = Battle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def battle_params
    params.require(:battle).permit(:initiator_id, :opponent_id, :status, :winner_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def leaderboard
    @players = Battle.joins("INNER JOIN users ON battles.winner_id = users.id")
      .select("users.name, COUNT(battles.winner_id) as total_wins")
      .group("battles.winner_id")
      .order("total_wins DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/battles/_battle.html.erb
<div id="<%= dom_id battle %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Initiator:</strong>
    <%= battle.initiator.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Opponent:</strong>
    <%= battle.opponent.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= battle.status %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Winner:</strong>
    <% if battle.winner != nil %>
      <%= battle.winner.name %>
    <% else %>
      NA
    <% end %>
  </p>
  <% if action_name != "show" %>
    <%= link_to "Show this battle", battle, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this battle', edit_battle_path(battle), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/battles/_form.html.erb
<%= form_with(model: battle, class: "contents") do |form| %>
  <% if battle.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
        <% battle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :initiator_id %>
    <%= form.text_field :initiator_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :opponent_id %>
    <%= form.text_field :opponent_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, value:'Pending', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/battles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing battle</h1>

  <%= render "form", battle: @battle %>

  <%= link_to "Show this battle", @battle, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to battles", battles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/battles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Battles</h1>
    <%= link_to 'New battle', new_battle_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="battles" class="min-w-full">
    <%= render @battles %>
  </div>
</div>

app/views/battles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New battle</h1>

  <%= render "form", battle: @battle %>

  <%= link_to 'Back to battles', battles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/battles/show.html.erb
<div class="mx-auto  w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render @battle %>
    <div>
      <div class="container flex justify-center mx-auto">
        <div class="flex flex-col">
          <div class="w-full">
            <div class="border-b border-gray-200 shadow">
              <div>
                <h1 class="text-3xl">Battle Logs</h1>
              </div>
              <br>
              <table class="divide-y divide-gray-300 ">
                <thead class="bg-gray-50">
                  <tr>
                    <th class="px-6 py-2 text-gray-500">
                      Step
                    </th>
                    <th class="px-6 py-2  text-gray-500">
                      Log
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-300">
                  <% @battle_logs.each_with_index do |battle, index| %>
                    <tr class="whitespace-nowrap">
                      <td class="px-6 py-4  text-gray-500">
                        <%= (index + 1) %>
                      </td>
                      <td class="px-6 py-4">
                        <div class=" text-gray-900">
                          <%= battle.log %>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= link_to 'Edit this battle', edit_battle_path(@battle), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this battle', battle_path(@battle), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to battles', battles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/index.html.erb
<div>
  <h1>Welcome, <%= current_user.name %>
  <br>
  <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete %>
</div>

app/views/home/leaderboard.html.erb
<div class="container flex justify-center mx-auto">
  <div class="flex flex-col">
    <div class="w-full">
      <div class="border-b border-gray-200 shadow">
        <div>
          <h1 class="text-3xl">Leaderboard</h1>
        </div>
        <br>
        <table class="divide-y divide-gray-300 ">
          <thead class="bg-gray-50">
            <tr>
              <th class="px-6 py-2 text-gray-500">
                Position
              </th>
              <th class="px-6 py-2  text-gray-500">
                Name
              </th>
              <th class="px-6 py-2 text-gray-500">
                Number of Wins
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-300">
            <% @players.each_with_index do |player, index| %>
              <tr class="whitespace-nowrap">
                <td class="px-6 py-4 text-xl text-gray-500">
                  #<%= (index + 1) %>
                </td>
                <td class="px-6 py-4">
                  <div class=" text-gray-900">
                    <%= player.name %>
                  </div>
                </td>
                <td class="px-6 py-4">
                  <div class=" text-gray-500"><%= player.total_wins %></div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Werewolves</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="grid h-screen place-items-center">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>